---
- name: IBM Spectrum Virtualize collection to create an FC host
  hosts: localhost
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  vars:
    clustername: <Your_IP_or_URL>
    domain:
    username: superuser
    password: <Your_Password>
    log_path: mkhost_playbook.debug
  tasks:
    - name: Define a new FC host
      ibm_svc_host:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        username: "{{ username }}"
        password: "{{ password }}"
        log_path: "{{ log_path | default('/tmp/playbook.debug') }}"
        name: ansible-host-svm12
        state: present
        fcwwpn: 100000109b46f496:100000109b46f497
        iogrp: 0:1:2:3
        protocol: scsi
        type: generic
