---
- name: Create a volume
  hosts: localhost
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  vars:
    clustername: <Your_IP_or_URL>
    domain:
    username: superuser
    password: <Your_Password>
    log_path: /tmp/mkhost_attach_playbook.debug
  tasks:
    - name: Create a new volume
      ibm_svc_vdisk:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        username: "{{ username }}"
        password: "{{ password }}"
        log_path: "{{ log_path | default('/tmp/create_vol_playbook.debug') }}"
        name: ansibleVol1
        state: present
        mdiskgrp: Pool0
        easytier: "off"
        size: "10"
        unit: "gb"
