---
- name: Using the IBM Spectrum Virtualize collection
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  tasks:
    - name: Gather info from storage
      ibm_svc_info:
        clustername: 129.40.188.157
        domain:
        username: superuser
        password: pwb0t048
        log_path: /tmp/info_playbook.debug
        name: gather_info
        state: info
        gather_subset: all
