---
- name: Map volume to host
  hosts: localhost
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  vars:
    clustername: <Your_IP_or_URL>
    domain:
    username: superuser
    password: <Your_Password>
    log_path: /tmp/mkhost_attach_playbook.debug
  tasks:
    - name: Map volume to host
      ibm_svc_vol_map:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        username: "{{ username }}"
        password: "{{ password }}"
        log_path: "{{ log_path | default('/tmp/map_vol_playbook.debug') }}"
        volname: ansibleVol1
        host: ansible-host-svm12
        state: present
